### ISSUE TITLE
Please make this repo private

### ISSUE THREAD

**Issue by ammonshepherd** [MoisesSanchez2020/phpmotors#1]
so it is harder for others to cheat. :)

**Comment by MoisesSanchez2020** [comment]
what do you mean, I want people to learn.

**Comment by ammonshepherd** [comment]
People don't learn by copying your code and turning it in as their own. And that's the only way I have seen your content be used. I'm sure you have great intentions, but it's not working.

This content is through a paid course (as you should know), and there is a professor, fellow students in a team, and tutors who all can help students learn the content. By keeping your repo public, all you are doing is giving answers to the "test".

How is keeping this repo public helping anyone learn? Give me real proof of that happening. I can give you proof of at least one student every semester copying code from open repos and turning it in as their own without any editing.

**Comment by MoisesSanchez2020** [comment]
Listen, I don't have your time to be checking in everybody's account. If you are a teacher please teach don't assume the student knows. I took this class at BYU-I and my teacher didn't say anything about making this repository private. 
If you have students coping code is because you are a bad teacher, do me a favor be a better teacher. PHP is complicated if you don't have someone taking the time to explain the code. My teacher was good and took the time to teach, you don't look like that. Stop and leave people alone.
